# Use Case
#### What is the shape of this array
```
a:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
```
#### Calculate the sum over axis=2 and axis=1. What will be their respective shape and dimensions?
#### What is the shape of the following array. Is it possible to broadcast to add the following array to the above array? If yes, good, else transform the above array without dropping any indices or axis, so that you can add the following array to it.
```
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
```

#### Sorting a 2-D array rows based in their values in the first column
##### Generate an array of shape 5x4 using randint

#### Partition a 5x4 array using np.partition over kth=3. What happens